title: Share your world
hero_image: images/banner.png
description: Build an interactive website to share a part of your world
version: 1
listed: false
copyedit: false
last_tested: "2024-3-25"
steps:
  - title: You will make
  - title: Build the home page
  - title: Style the page
    completion:
      - engaged
  - title: Choose your colours
  - title: Add interactivity
    completion:
      - internal
  - title: Build a timeline page
    completion:
      - external
  - title: Challenge
    challenge: true
